# Generated by Django 5.2 on 2025-04-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('jss', 'JavaScript'), ('html', 'HTML'), ('cpp', 'C++')], max_length=30),
        ),
    ]
